const quizData = [
  {
    question: "How did Harry get the scar on his forehead?",
    a: "In a quiddich accident",
    b: "He was attacked by a basilisk",
    c: "Lord Voldemort tried to kill him when he was a baby",
    d: "He was bitten by a werewolf",
    correct: "c",
  },
  {
    question: "Name Ron Weasley's pet rat",
    a: "Scratchy",
    b: "Scabbers",
    c: "Itchy",
    d: "Splinter",
    correct: "b",
  },
  {
    question: "Which animal is associated with Hufflepuff?",
    a: "Bear",
    b: "Badger",
    c: "Wolf",
    d: "Fox",
    correct: "b",
  },
  {
    question: "When unearthed, a mandrake will do what?",
    a: "Dance",
    b: "Burp",
    c: "Scream",
    d: "Laugh",
    correct: "c",
  },
  {
    question: "What creature is Aragog?",
    a: "Acromantula",
    b: "Dragon",
    c: "Hippogriff",
    d: "Boggart",
    correct: "a",
  },
  {
    question: "Who is Harry Potter's godfather?",
    a: "Remus Lupin",
    b: "Peter Pettigrew",
    c: "Lucius Malfoy",
    d: "Sirius Black",
    correct: "d",
  },
  {
    question: "Who was Hemione’s date at Hogwarts’ Yule Ball?",
    a: "Harry Potter",
    b: "Viktor Krum",
    c: "Ron Weasley",
    d: "Neville Longbottom",
    correct: "b",
  },
  {
    question: "The potion Felix Felicis is commonly known as?",
    a: "Liquid Luck",
    b: "Eternal love",
    c: "The Dark Knight",
    d: "Сonqueror of death",
    correct: "a",
  },
  {
    question: "What spell did Harry use to kill Lord Voldemort?",
    a: "Expelliarmus",
    b: "Expecto Patronum",
    c: "Avada Kedavra",
    d: "Accio",
    correct: "a",
  },
  {
    question: 'Finish the quote: "After all this time?..."',
    a: "Never",
    b: "Forever",
    c: "Always",
    d: "Again",
    correct: "c",
  },
];
